create table `shop` (
    `idx` int(12) NOT NULL,
    `shop_id` varchar(255) NOT NULL,
    `shop_password` varchar(255) NOT NULL,
    `shop_name` varchar(255) NOT NULL,
    `shop_address` varchar(255) NOT NULL,
    `ip_address` varchar(30) default null,
    `shop_init_time` datetime NOT NULL,
    `shop_time` datetime NOT NULL,
    `deny` tinyInt default null,
    `etc` text default NULL,
    `des` text default NULL,
    `shop_log` text default NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
